package com.arcbank.sucursales.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.arcbank.sucursales.converter.LocalDateConverter;
<<<<<<< Updated upstream
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;

=======
import lombok.Data;
>>>>>>> Stashed changes
import java.time.LocalDate;

<<<<<<< Updated upstream
@DynamoDBTable(tableName = "sucursales")
@Getter
@Setter
public class Sucursal {

    @Id
    @DynamoDBHashKey
=======
@Data
@DynamoDBTable(tableName = "switch-sucursales")
public class Sucursal {

    @DynamoDBHashKey(attributeName = "id")
>>>>>>> Stashed changes
    @DynamoDBAutoGeneratedKey
    private String idSucursal;

    @DynamoDBAttribute
<<<<<<< Updated upstream
=======
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "codigoUnico-index")
>>>>>>> Stashed changes
    private String codigoUnico;

    @DynamoDBAttribute
    private String nombre;

    @DynamoDBAttribute
    private String direccion;

    @DynamoDBAttribute
    private String telefono;

    @DynamoDBAttribute
    private Double latitud;

    @DynamoDBAttribute
    private Double longitud;

    @DynamoDBAttribute
    private String estado;

<<<<<<< Updated upstream
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    @DynamoDBAttribute
=======
    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
>>>>>>> Stashed changes
    private LocalDate fechaApertura;

    @DynamoDBAttribute
    private EntidadBancaria entidadBancaria;

    @DynamoDBAttribute
    private Ubicacion ubicacion;

    public Sucursal() {
    }

    public Sucursal(String idSucursal) {
        this.idSucursal = idSucursal;
    }
<<<<<<< Updated upstream

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;
        Sucursal sucursal = (Sucursal) o;
        return Objects.equals(idSucursal, sucursal.idSucursal);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idSucursal);
    }

    @Override
    public String toString() {
        return "Sucursal{" +
                "idSucursal='" + idSucursal + '\'' +
                ", codigoUnico='" + codigoUnico + '\'' +
                ", nombre='" + nombre + '\'' +
                ", direccion='" + direccion + '\'' +
                ", telefono='" + telefono + '\'' +
                ", latitud=" + latitud +
                ", longitud=" + longitud +
                ", estado='" + estado + '\'' +
                '}';
    }
=======
>>>>>>> Stashed changes
}
